"use client";

import { useState } from "react";
import Link from "next/link";
import { Activity, Box, Truck, AlertTriangle, CheckCircle2, TrendingUp, FileText, Download, Loader2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function Dashboard() {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerateReport = () => {
    setIsGenerating(true);
    
    // Simulate generation time
    setTimeout(() => {
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>ChipTrace - Executive Supply Chain Report</title>
          <style>
            body { font-family: 'Inter', system-ui, sans-serif; color: #111827; max-width: 800px; margin: 0 auto; padding: 40px; }
            .header { border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
            h1 { color: #1e3a8a; margin: 0 0 10px 0; }
            .meta { color: #6b7280; font-size: 14px; }
            .section { margin-bottom: 40px; }
            h2 { color: #1f2937; border-bottom: 1px solid #e5e7eb; padding-bottom: 10px; margin-bottom: 20px; }
            .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }
            .metric { background: #f3f4f6; padding: 20px; border-radius: 8px; text-align: center; }
            .metric-val { font-size: 24px; font-weight: bold; color: #2563eb; margin-top: 10px; }
            table { w-full; border-collapse: collapse; margin-top: 20px; width: 100%; }
            th, td { border: 1px solid #e5e7eb; padding: 12px; text-align: left; }
            th { background: #f8fafc; font-weight: 600; }
            .high-risk { color: #dc2626; font-weight: bold; }
          </style>
        </head>
        <body onload="window.print()">
          <div class="header">
            <h1>Executive Supply Chain & Quality Report</h1>
            <div class="meta">Generated by ChipTrace AI &bull; ${new Date().toLocaleDateString()}</div>
          </div>
          
          <div class="section">
            <h2>1. Key Performance Indicators</h2>
            <div class="grid">
              <div class="metric"><div>Total Active Batches</div><div class="metric-val">1,284</div></div>
              <div class="metric"><div>Global Defect Rate</div><div class="metric-val">2.4%</div></div>
              <div class="metric"><div>Total Inventory</div><div class="metric-val">82.4K Units</div></div>
            </div>
          </div>

          <div class="section">
            <h2>2. Active Critical Risks</h2>
            <table>
              <tr><th>Risk ID</th><th>Category</th><th>Description</th><th>Severity</th></tr>
              <tr><td>SHIP-88231</td><td>Logistics</td><td>Port congestion + customs delay</td><td class="high-risk">High</td></tr>
              <tr><td>MCU-AX45</td><td>Inventory</td><td>Stockout predicted in 5 days</td><td class="high-risk">High</td></tr>
              <tr><td>BATCH-004823</td><td>Quality</td><td>Batch failed final ML inspection</td><td class="high-risk">Critical</td></tr>
            </table>
          </div>

          <div class="section">
            <h2>3. Quality Control Summary</h2>
            <p>The AI Vision Inspection pipeline has processed 14,200 chips in the last 7 days. Overall yield remains stable at 97.6%. 
            Corrosion and bent pins account for 68% of all identified anomalies. Factory A in Taiwan is currently outperforming Global benchmarks by 2.1%.</p>
          </div>
        </body>
        </html>
      `;
      
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      window.open(url, '_blank');
      
      setIsGenerating(false);
    }, 1500);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Dashboard</h1>
          <p className="text-muted-foreground mt-1">
            Overview of your supply chain and quality metrics.
          </p>
        </div>
        <button 
          onClick={handleGenerateReport}
          disabled={isGenerating}
          className="flex items-center gap-2 px-4 py-2 bg-primary/20 text-primary border border-primary/30 rounded-lg hover:bg-primary/30 transition-colors shadow-[0_0_15px_rgba(14,165,233,0.2)] disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isGenerating ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <FileText className="w-4 h-4" />
          )}
          <span className="text-sm font-semibold">{isGenerating ? "Compiling Data..." : "Generate PDF Report"}</span>
          {!isGenerating && <Download className="w-3 h-3 ml-1" />}
        </button>
      </div>
      
      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
        {[
          { title: "Active Batches", value: "1,284", icon: Activity, color: "text-blue-400", bg: "from-blue-500/20 to-blue-500/5", border: "group-hover:border-blue-500/50" },
          { title: "In Transit", value: "327", icon: Truck, color: "text-amber-400", bg: "from-amber-500/20 to-amber-500/5", border: "group-hover:border-amber-500/50" },
          { title: "Inventory", value: "82.4K", icon: Box, color: "text-emerald-400", bg: "from-emerald-500/20 to-emerald-500/5", border: "group-hover:border-emerald-500/50" },
          { title: "Defect Rate", value: "2.4%", icon: CheckCircle2, color: "text-rose-400", bg: "from-rose-500/20 to-rose-500/5", border: "group-hover:border-rose-500/50" },
          { title: "Delayed", value: "18", icon: TrendingUp, color: "text-orange-400", bg: "from-orange-500/20 to-orange-500/5", border: "group-hover:border-orange-500/50" },
          { title: "SC Risk", value: "7 High", icon: AlertTriangle, color: "text-red-500", bg: "from-red-500/20 to-red-500/5", border: "group-hover:border-red-500/50" },
        ].map((kpi, i) => (
          <Card key={i} className={`group transition-all duration-300 ${kpi.border} bg-white/[0.02] hover:bg-white/[0.04] overflow-hidden relative`}>
            {/* Subtle top glow */}
            <div className={`absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r ${kpi.bg} opacity-50`} />
            <CardContent className="p-5 flex flex-col gap-4 relative z-10">
              <div className="flex justify-between items-start">
                <p className="text-[13px] font-medium text-muted-foreground tracking-wide uppercase">{kpi.title}</p>
                <div className={`p-2 rounded-xl bg-gradient-to-br ${kpi.bg} border border-white/5 shadow-inner`}>
                  <kpi.icon className={`w-4 h-4 ${kpi.color}`} />
                </div>
              </div>
              <h3 className="text-3xl font-semibold tracking-tight text-white/90">{kpi.value}</h3>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="col-span-2">
          <CardHeader className="border-b border-white/5 pb-4">
            <CardTitle className="text-lg font-medium text-white/90">Supply Chain Digital Twin</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <div className="h-[400px] w-full bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-primary/10 via-transparent to-transparent flex flex-col items-center justify-center relative overflow-hidden">
              {/* Subtle grid background */}
              <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:40px_40px] [mask-image:radial-gradient(ellipse_at_center,black_40%,transparent_70%)]" />
              
              <div className="flex justify-between items-center w-full max-w-3xl px-8 z-10 relative">
                <Node label="Taiwan Factory" value="12.5k / day" status="success" />
                
                {/* Animated Connection Line */}
                <div className="flex-1 h-[2px] bg-white/10 relative mx-4">
                   <div className="absolute top-0 left-0 h-full bg-gradient-to-r from-transparent via-primary to-transparent w-1/2 animate-[pulse_2s_ease-in-out_infinite]" />
                   <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 px-3 py-1 bg-[#030712] text-[11px] rounded-full border border-primary/30 text-primary font-mono shadow-[0_0_15px_rgba(14,165,233,0.3)]">BATCH-2026-004821</div>
                </div>
                
                <Node label="Wafer Testing" value="98.7% Yield" status="warning" />
                
                <div className="flex-1 h-[2px] bg-white/10 relative mx-4" />
                
                <Node label="Global Warehouse" value="82k Stock" status="success" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="flex flex-col">
          <CardHeader className="border-b border-white/5 pb-4">
            <CardTitle className="text-lg font-medium text-white/90">Live Risk Feed</CardTitle>
          </CardHeader>
          <CardContent className="flex-1 p-0 flex flex-col">
            {[
              { id: "SHIP-88231", type: "Logistics", message: "Port congestion + customs delay", severity: "high", time: "10m ago" },
              { id: "MCU-AX45", type: "Inventory", message: "Stockout predicted in 5 days", severity: "high", time: "1h ago" },
              { id: "SUP-03", type: "Supplier", message: "Delivery performance decreased 23%", severity: "warning", time: "2h ago" },
              { id: "BATCH-2026-004823", type: "Quality", message: "Batch failed final testing", severity: "high", time: "5h ago" },
            ].map((risk, i) => (
              <Link href="/risk" key={i} className="flex gap-4 items-start p-5 border-b border-white/5 last:border-0 hover:bg-white/[0.02] transition-colors cursor-pointer group">
                <div className={`mt-0.5 rounded-xl p-2 ${risk.severity === 'high' ? 'bg-red-500/10 text-red-400 shadow-[0_0_15px_rgba(239,68,68,0.15)] group-hover:shadow-[0_0_20px_rgba(239,68,68,0.3)]' : 'bg-amber-500/10 text-amber-400 shadow-[0_0_15px_rgba(245,158,11,0.1)]'}`}>
                  <AlertTriangle className="w-4 h-4" />
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between mb-1">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-semibold text-white/90">{risk.id}</span>
                      <Badge variant="outline" className="text-[10px] h-5 py-0 leading-none bg-white/[0.03] border-white/10 text-muted-foreground">{risk.type}</Badge>
                    </div>
                    <span className="text-[10px] text-muted-foreground/70">{risk.time}</span>
                  </div>
                  <p className="text-xs text-muted-foreground group-hover:text-white/70 transition-colors">{risk.message}</p>
                </div>
              </Link>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function Node({ label, value, status }: { label: string, value: string, status: string }) {
  const isSuccess = status === 'success';
  return (
    <div className="flex flex-col items-center gap-3 relative group cursor-pointer">
      {/* Node Glow */}
      <div className={`absolute inset-0 bg-${isSuccess ? 'emerald' : 'amber'}-500/20 blur-xl rounded-full scale-150 opacity-0 group-hover:opacity-100 transition-opacity`} />
      
      <div className={`w-14 h-14 rounded-2xl border flex items-center justify-center bg-[#030712] relative z-10 transition-all duration-300 ${isSuccess ? 'border-emerald-500/50 text-emerald-400 shadow-[0_0_20px_rgba(16,185,129,0.15)] group-hover:border-emerald-400 group-hover:shadow-[0_0_30px_rgba(16,185,129,0.3)]' : 'border-amber-500/50 text-amber-400 shadow-[0_0_20px_rgba(245,158,11,0.15)] group-hover:border-amber-400 group-hover:shadow-[0_0_30px_rgba(245,158,11,0.3)]'}`}>
        <Activity className="w-6 h-6" />
      </div>
      <div className="text-center relative z-10">
        <p className="text-[13px] font-semibold text-white/90 whitespace-nowrap">{label}</p>
        <p className="text-[11px] text-muted-foreground whitespace-nowrap mt-0.5">{value}</p>
      </div>
    </div>
  )
}
